spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      idle-timeout: 600000
      maximum-pool-size: 50


---
spring:
  config:
    activate:
      on-profile: suyh, sit

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.34:3306/flink-cds?useSSL=false&characterEncoding=UTF-8
    username: flink-cds
    password: flink-cds
    hikari:
      connection-timeout: 3000
      idle-timeout: 600000
      maximum-pool-size: 5

---
spring:
  config:
    activate:
      on-profile: prod








