

---
spring:
  config:
    activate:
      on-profile: suyh, sit

cds:
  flink:
    batch:
      cds-rmq:
        sink:
          exchange: flink_output_topic_exchange
          routing-key-cohort: cohort_key
          connect:
            host: 192.168.8.34
            port: 5672
            user-name: admin
            password: aiteer
            virtual-host: /suyh-flinkhost


