

spring:
  redis:
    timeout: PT1S
    connect-timeout: PT5S
    lettuce:
      pool:
        enabled: true
        max-active: 1000
        max-wait: PT2S
        max-idle: 500
        min-idle: 10


---
spring:
  config:
    activate:
      on-profile: suyh


  redis:
    host: 192.168.8.34
    port: 6379 # 端口
    password: aiteer
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

---
spring:
  config:
    activate:
      on-profile: sit
  redis:
    host: localhost
    port: 6379 # 端口
    password: aiteer
    database: 0

---
spring:
  config:
    activate:
      on-profile: prod

  redis:
    host: localhost
    port: 6379 # 端口
