
cds:
  flink:
    stream:
      cds-rmq:
        source:
          prefetch-count: 20000
        sink:
          exchange: flink_output_topic_exchange
          routing-key-cohort: cohort_key
          routing-key-paid-retention: paid_retention_key

---
spring:
  config:
    activate:
      on-profile: suyh, sit

cds:
  flink:
    stream:
      cds-rmq:
        source:
          prefetch-count: 20
          connect:
            host: 192.168.8.34
            port: 5672
            user-name: admin
            password: aiteer
            virtual-host: /suyh-flinkhost
        sink:
          connect:
            host: 192.168.8.34
            port: 5672
            user-name: admin
            password: aiteer
            virtual-host: /suyh-flinkhost
    common:
      cohort-thread-pool:
        core-pool-size: 4
        maximum-pool-size: 32
        keep-alive-time: 60
        unit: seconds
        work-queue: 100000


