




cds:
  flink:
    stream:
      cds-rmq:
        source:
          prefetch-count: 20000
          queue-user-registry: poly_tb_user_pre
          queue-user-login: poly_tb_user_login_pre
          queue-user-recharge: poly_tb_recharge_pre
          queue-user-withdrawal: poly_tb_withdrawal_pre
          connect:
            host: 192.168.8.34
            port: 5672
            user-name: admin
            password: aiteer
            virtual-host: /flinkhost
        sink:
          exchange: flink_output_topic_exchange
          routing-key-cohort: cohort_key
          routing-key-paid-retention: paid_retention_key
          connect:
            host: 192.168.8.34
            port: 5672
            user-name: admin
            password: aiteer
            virtual-host: /flinkhost
