


spring:
  main:
    web-application-type: none
  config:
    import:
      - application-cds.yaml
      - application-datasource.yaml
      - application-log.yaml
      - application-redis.yaml




