


spring:
  config:
    import:
      - application-cache.yaml
      - application-datasource.yaml
      - application-json.yaml
      - application-log.yaml
      - application-suyh.yaml
      - application-web.yaml



