

spring:
  redis:
    timeout: PT1S
    connect-timeout: PT5S
    host: isuyh.com
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        enabled: true
        max-active: 1000
        max-wait: PT2S
        max-idle: 500
        min-idle: 10
