


spring:
  datasource:
    url: jdbc:mysql://43.139.78.193:3306/suyh-personal?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: suyh-personal
    password: suyh-personal