

spring:
  profiles:
    # 在生产环境，该配置项为固定值(prod)，请勿修改。
    active: prod


  # mysql 数据库的相关配置
  datasource:
    # 该配置对应原 flink-job.properties 文件中的: mysql_url=mysql_url
    url: jdbc:mysql://192.168.8.34:3306/flink-cds?useSSL=false&characterEncoding=UTF-8
    # 该配置对应原 flink-job.properties 文件中的: mysql_username=mysql_username
    username: flink-cds
    # 该配置对应原 flink-job.properties 文件中的: mysql_password=mysql_password
    password: flink-cds
    # 当前使用的数据源的连接池组件是hikari
    hikari:
      # 连接超时时间，单位：ms
      connection-timeout: 3000
      # 连接空闲超时时间，单位：ms
      idle-timeout: 600000
      # 最大连接池数量
      maximum-pool-size: 50

  # redis 配置
  redis:
    # 默认值：localhost
    host: localhost
    # 默认值：6379
    port: 6379
    # 密码
    password: password
    # redis 索引序号，正常情况为：0-15
    database: 0
    # 读取超时
    timeout: PT1S
    # 连接超时
    connect-timeout: PT5S
    # lettuce 连接池配置
    lettuce:
      pool:
        # 是否启用连接池
        enabled: true
        # 闲置连接的最大值
        max-idle: 500
        # 闲置连接最小值
        min-idle: 10
        # 最大连接数
        max-active: 1000
        # 连接池满时，最大阻塞时间
        # PT2S 表示 2 秒钟
        max-wait: PT2S
        # 闲置连接驱逐器，运行间隔时间。为正时驱逐器启用，否则不执行闲置连接驱逐。
        # PT5M 表示 5 分钟
        time-between-eviction-runs: PT5M
    # 如果使用redis 硝兵模式，需要使用sentinel标签，以及相对应的配置项，具体配置项，在这里不展开说明。
    # sentinel:
    # 如果使用redis 集群模式，需要使用cluster标签，以及相对应的配置项，具体配置项，在这里不展开说明。
    # cluster:


cds:
  flink:
    # flink 流模式配置
    stream:
      # rabbitmq 配置
      cds-rmq:

        # rabbitmq source 的相关配置
        source:
          # 每条rabbitmq source 一次预取的数量，默认值：20000
          prefetch-count: 20000
          # 用户注册队列名，默认值：poly_tb_user_pre
          queue-user-registry: poly_tb_user_pre
          # 用户登录队列名，默认值：poly_tb_user_login_pre
          queue-user-login: poly_tb_user_login_pre
          # 用户充值队列名，默认值：poly_tb_recharge_pre
          queue-user-recharge: poly_tb_recharge_pre
          # 用户撤回队列名，默认值：poly_tb_withdrawal_pre
          queue-user-withdrawal: poly_tb_withdrawal_pre
          # rabbitmq source 连接的相关配置
          connect:
            host: 192.168.8.34
            port: 5672
            user-name: admin
            password: aiteer
            virtual-host: /flinkhost

        # rabbitmq sink 的相关配置
        sink:
          # 该配置对应原 flink-job.properties 文件中的: exchange=flink_output_topic_exchange
          exchange: flink_output_topic_exchange
          # 该配置对应原 flink-job.properties 文件中的: cohort_routingKey=cohort_key
          routing-key-cohort: cohort_key
          # 该配置对应原 flink-job.properties 文件中的: cohort_routingKey_paid=paid_retention_key
          routing-key-paid-retention: paid_retention_key
          # rabbitmq sink 连接的相关配置
          connect:
            host: 192.168.8.34
            port: 5672
            user-name: admin
            password: aiteer
            virtual-host: /flinkhost





